#!/usr/bin/env python3
# FPP - FreeBSD Pack Parser
# Parses a custom .fpsf file format into an install script.
# .fpsf stands for FreeBSD Pack Setup File.

# The file format of .fpsf files is as follows:
# The first line is a human-readable description of what the
# script created by the .fpsf file will do.
# The second line is a space-separated list of pkg packages
# to be installed.
# All further lines are filenames of configuration files, followed
# by a tab-preceded list of lines to add to those files. The tab-preceded
# lines can also start with a dash character ('-') followed by a tab to
# signify that a line with that content is to be *removed* from the file.
import sys

if len (sys.argv) != 2:
	print('Usage: fpsf.py [file.fpsf]')
else:
	f = open(sys.argv[1], 'r')
	i = 0
	curfile = ''
	for line in f:
		if i == 0:
			print('#!/bin/sh')
			print('#', line)
			print('# GENERATED BY FPP (FreeBSD Pack Parser) from a .fpsf (FreeBSD Pack Setup File) file.')
		if i == 1:
			print('pkg install -y', line)
		if i > 1:
			escaped = line[1:-1].replace('"', '\\"')
			if line[0] == '-':
				escaped = escaped[1:]
			if line.find('\t') == 0:
				print('if ! grep -Fxq "%(escaped)s" %(curfile)s' % locals())
				print('then')
				print('\techo "%(escaped)s" >> %(curfile)s' % locals())
				print('fi')
			elif line.find('-\t') == 0:
				print('if grep -Fxq "%(escaped)s" %(curfile)s' % locals())
				print('then')
				print('\tsed "/%(escaped)s/d" %(curfile)s' % locals())
				print('fi')
			else:
				curfile = line.rstrip()
		i += 1
