#!/bin/sh
# Installs Wacom Drivers for FreeBSD

# GENERATED BY FPP (FreeBSD Pack Parser) from a .fpsf (FreeBSD Pack Setup File) file.
pkg install -y xf86-input-wacom webcamd xorg-server

if ! grep -Fxq "cuse4bsd_load=\"YES\"" /boot/loader.conf
then
	echo "cuse4bsd_load=\"YES\"" >> /boot/loader.conf
fi
if ! grep -Fxq "devd_enable=\"YES\"" /etc/rc.conf
then
	echo "devd_enable=\"YES\"" >> /etc/rc.conf
fi
if ! grep -Fxq "hald_enable=\"YES\"" /etc/rc.conf
then
	echo "hald_enable=\"YES\"" >> /etc/rc.conf
fi
if ! grep -Fxq "webcamd_enable=\"YES\"" /etc/rc.conf
then
	echo "webcamd_enable=\"YES\"" >> /etc/rc.conf
fi
