#!/bin/sh
# Installs K Desktop Environment for FreeBSD

# GENERATED BY FPP (FreeBSD Pack Parser) from a .fpsf (FreeBSD Pack Setup File) file.
pkg install -y x11/kde4

if ! grep -Fxq "dbus_enable=\"YES\"" /etc/rc.conf
then
	echo "dbus_enable=\"YES\"" >> /etc/rc.conf
fi
if ! grep -Fxq "hald_enable=\"YES\"" /etc/rc.conf
then
	echo "hald_enable=\"YES\"" >> /etc/rc.conf
fi
if ! grep -Fxq "kdm4_enable=\"YES\"" /etc/rc.conf
then
	echo "kdm4_enable=\"YES\"" >> /etc/rc.conf
fi
