#!/bin/sh
# Installs the apps that I like to use on FreeBSD.

# GENERATED BY FPP (FreeBSD Pack Parser) from a .fpsf (FreeBSD Pack Setup File) file.
pkg install -y git bash gimp firefox neovim python3

